#include <iostream>
#include <fstream>
#include <string>
using namespace std;

// Function to generate the HTML content
void generateHtml() {
    std::ofstream file("index.html");

    file << "<!DOCTYPE html>\n";
    file << "<html>\n";
    file << "<head>\n";
    file << "<title>My C++ Project</title>\n";
    file << "<style>\n";
    file << "body { font-family: Arial, sans-serif; background-color: #f0f0f0; }\n";
    file << "h1 { color: #333; }\n";
    file << "p { color: #666; }\n";
    file << "</style>\n";
    file << "</head>\n";
    file << "<body>\n";
    file << "<h1>Hello, World!</h1>\n";
    file << "<p>This is a simple HTML page generated by a C++ program.</p>\n";
    file << "<p>  *       *    * * * * *    *       *    *********    *       *    * * * * *    *       *    ---------</p>\n";
    file << "<p>  *       *    *       *    * *     *    *            * *   * *    *       *    * *     *    :        :</p>\n";
    file << "<p>  * * * * *    * * * * *    *   *   *    *    ****    *   *   *    * * * * *    *   *   *    :        0</p>\n";
    file << "<p>  *       *    *       *    *     * *    *       *    *       *    *       *    *     * *    :       \\:/</p>\n";
    file << "<p>  *       *    *       *    *       *    *********    *       *    *       *    *       *    :       / \\  </p>\n";
    file << "<p>                                                                                             :</p>\n";
    file << "<p>                                                                                           ========\n";
    file << "</body>\n";
    file << "</html>\n";

    file.close();
}

int main() {
    // Call the function to generate the HTML file
    generateHtml();
    return 0;
}
